version: '3.3'
services:
  alist:
    restart: always
    volumes:
      - '/etc/alist:/opt/alist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
      DB_HOST: "ap-northeast.connect.psdb.cloud"
      DB_NAME: "aesir"
      DB_PASS: "pscale_pw_JJs88T8nx75U1JybCRbVCD89LLOjlywyiW9c38CRIS0"
      DB_PORT: "3306"
      DB_SSL_MODE: "true"
      DB_TABLE_PREFIX: "alist_"
      DB_TYPE: "mysql"
      DB_USER: "fy2sesn9v80rb5vjjgk8"
    container_name: alist
    image: 'xhofe/alist:latest'
